/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/iphone_12.glb -t 
*/

import * as THREE from 'three'
import React, { useEffect, useMemo } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'
import { GLTF } from 'three-stdlib'

type ActionName = 'Take 001'

interface GLTFAction extends THREE.AnimationClip {
  name: ActionName
}

type GLTFResult = GLTF & {
  nodes: {
    front_panel_screw04_1: THREE.Mesh
    front_panel_screw03_1: THREE.Mesh
    front_panel_screw02_1: THREE.Mesh
    front_panel_screw01_1: THREE.Mesh
    earspeaker_2: THREE.Mesh
    earspeaker_3: THREE.Mesh
    earspeaker_4: THREE.Mesh
    front_panel_2: THREE.Mesh
    front_panel_3: THREE.Mesh
    front_panel_4: THREE.Mesh
    front_panel_5: THREE.Mesh
    front_panel_6: THREE.Mesh
    front_panel_7: THREE.Mesh
    back_cam_hole2_2: THREE.Mesh
    back_cam_hole2_3: THREE.Mesh
    back_cam_hole2_4: THREE.Mesh
    back_cam_hole2_5: THREE.Mesh
    back_cam_hole1_2: THREE.Mesh
    back_cam_hole1_3: THREE.Mesh
    back_cam_hole1_4: THREE.Mesh
    back_cam_hole1_5: THREE.Mesh
    back_cam_flashlight_hole_2: THREE.Mesh
    back_cam_flashlight_hole_3: THREE.Mesh
    back_cam_glass_2: THREE.Mesh
    back_cam_glass_3: THREE.Mesh
    back_cam_glass_4: THREE.Mesh
    back_cover_2: THREE.Mesh
    back_cover_3: THREE.Mesh
    battery_2: THREE.Mesh
    battery_3: THREE.Mesh
    battery_4: THREE.Mesh
    backplate_2: THREE.Mesh
    backplate_3: THREE.Mesh
    back_cam_cover_1: THREE.Mesh
    back_cam_2: THREE.Mesh
    back_cam_3: THREE.Mesh
    back_cam_4: THREE.Mesh
    antenn_2: THREE.Mesh
    antenn_3: THREE.Mesh
    antenn_4: THREE.Mesh
    btn_off_1: THREE.Mesh
    btn_off_gears_2: THREE.Mesh
    btn_off_gears_3: THREE.Mesh
    btn_volume_down_1: THREE.Mesh
    btn_volume_down_gears_2: THREE.Mesh
    btn_volume_down_gears_3: THREE.Mesh
    btn_volume_off_2: THREE.Mesh
    btn_volume_off_3: THREE.Mesh
    btn_volume_up_1: THREE.Mesh
    btn_volume_up_gears_2: THREE.Mesh
    btn_volume_up_gears_3: THREE.Mesh
    charging_cable_2: THREE.Mesh
    charging_cable_3: THREE.Mesh
    charging_cable_4: THREE.Mesh
    charging_port_2: THREE.Mesh
    charging_port_3: THREE.Mesh
    charging_port_4: THREE.Mesh
    cover_1: THREE.Mesh
    cover_flex_cables_1: THREE.Mesh
    flashlight_2: THREE.Mesh
    flashlight_3: THREE.Mesh
    flashlight_4: THREE.Mesh
    flashlight_dummy_2: THREE.Mesh
    flashlight_dummy_3: THREE.Mesh
    front_cam_2: THREE.Mesh
    front_cam_3: THREE.Mesh
    front_cam_4: THREE.Mesh
    front_cam_bracket_2: THREE.Mesh
    front_cam_bracket_3: THREE.Mesh
    front_sensor_2: THREE.Mesh
    front_sensor_3: THREE.Mesh
    front_sensor_4: THREE.Mesh
    front_sensor_5: THREE.Mesh
    inside_cam_holder_1: THREE.Mesh
    magnets_1: THREE.Mesh
    mic_2: THREE.Mesh
    mic_3: THREE.Mesh
    motherboard_2: THREE.Mesh
    motherboard_3: THREE.Mesh
    motherboard_4: THREE.Mesh
    motherboard_cables_cover_1: THREE.Mesh
    motherboard_cover_1: THREE.Mesh
    screw_pentalobe_2: THREE.Mesh
    screw_pentalobe_3: THREE.Mesh
    Screw01_1: THREE.Mesh
    Screw02_1: THREE.Mesh
    Screw03_1: THREE.Mesh
    Screw04_1: THREE.Mesh
    Screw05_1: THREE.Mesh
    Screw06_1: THREE.Mesh
    Screw08_1: THREE.Mesh
    Screw09_1: THREE.Mesh
    Screw10_1: THREE.Mesh
    Screw11_1: THREE.Mesh
    Screw12_1: THREE.Mesh
    Screw13_1: THREE.Mesh
    Screw14_1: THREE.Mesh
    Screw15_1: THREE.Mesh
    Screw16_1: THREE.Mesh
    Screw17_1: THREE.Mesh
    Screw18_1: THREE.Mesh
    Screw19_1: THREE.Mesh
    Screw20_1: THREE.Mesh
    Screw21_1: THREE.Mesh
    Screw22_1: THREE.Mesh
    Screw23_1: THREE.Mesh
    Screw24_1: THREE.Mesh
    Screw25_1: THREE.Mesh
    Screw26_1: THREE.Mesh
    Screw27_1: THREE.Mesh
    Screw28_1: THREE.Mesh
    Screw29_1: THREE.Mesh
    Screw30_1: THREE.Mesh
    Screw31_1: THREE.Mesh
    Screw32_1: THREE.Mesh
    Screw33_1: THREE.Mesh
    Screw34_1: THREE.Mesh
    Screw35_1: THREE.Mesh
    Screw36_1: THREE.Mesh
    Screw37_1: THREE.Mesh
    Screw38_1: THREE.Mesh
    Screw39_1: THREE.Mesh
    Screw41_1: THREE.Mesh
    Screw42_1: THREE.Mesh
    Screw43_1: THREE.Mesh
    Screw44_1: THREE.Mesh
    simholder_2: THREE.Mesh
    simholder_3: THREE.Mesh
    simholder_box_2: THREE.Mesh
    simholder_box_3: THREE.Mesh
    simholder_box_4: THREE.Mesh
    simholder_cable_cover_1: THREE.Mesh
    speaker_2: THREE.Mesh
    speaker_3: THREE.Mesh
    speaker_cover_2: THREE.Mesh
    speaker_cover_3: THREE.Mesh
    taptick_2: THREE.Mesh
    taptick_3: THREE.Mesh
    taptick_4: THREE.Mesh
    wifi_antenn_2: THREE.Mesh
    wifi_antenn_3: THREE.Mesh
    wifi_antenn_4: THREE.Mesh
    Screw045: THREE.Mesh
    Screw_special_01_1: THREE.Mesh
    Screw_special_02_1: THREE.Mesh
    wireless_charge_2: THREE.Mesh
    wireless_charge_3: THREE.Mesh
    wireless_charge_4: THREE.Mesh
    Screw048: THREE.Mesh
    Screws_special_003_1: THREE.Mesh
    Screw40_1: THREE.Mesh
    glue_sticker_1: THREE.Mesh
    grid_wires_1: THREE.Mesh
    inside_body_1: THREE.Mesh
    inside_power_port_1: THREE.Mesh
    profile_housing_bottom_1: THREE.Mesh
    profile_housing_dummies_1: THREE.Mesh
    profile_housing_left_1: THREE.Mesh
    profile_housing_right_1: THREE.Mesh
    profile_housing_top_1: THREE.Mesh
  }
  materials: {
    mat_metal: THREE.MeshStandardMaterial
    mat_plastic_parts: THREE.MeshStandardMaterial
    mat_parts: THREE.MeshStandardMaterial
    mat_screen_plastic: THREE.MeshStandardMaterial
    mat_glass: THREE.MeshStandardMaterial
    mat_screen: THREE.MeshStandardMaterial
    mat_color_body: THREE.MeshStandardMaterial
    mat_color_housing: THREE.MeshStandardMaterial
    mat_color_plastic: THREE.MeshStandardMaterial
    mat_plastic_parts: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const group = React.useRef<THREE.Group>(null)
  const { nodes, materials, animations } = useGLTF('/models/iphone_12.glb') as GLTFResult
  const { actions } = useAnimations(animations, group)

  // Autoplay the exploded animation Take 001 slowly
  useEffect(() => {
    const action = actions['Take 001']
    if (action) {
      action.play()
      action.setEffectiveTimeScale(0.18) // slow, elegant disassembly/reassembly
    }
  }, [actions])

  const reduceMotion = useMemo(() => {
    if (typeof window === 'undefined') return false
    return window.matchMedia('(prefers-reduced-motion: reduce)').matches
  }, [])

  useFrame((state) => {
    if (!group.current || reduceMotion) return

    const isMobile = window.innerWidth < 768

    if (isMobile) {
      // Very gentle auto-floating and slow rotation on mobile
      const elapsedTime = state.clock.getElapsedTime()
      group.current.position.y = Math.sin(elapsedTime * 0.6) * 0.08
      group.current.rotation.y = elapsedTime * 0.05
    } else {
      // Lerped mouse-controlled rotation on desktop
      const targetX = state.mouse.y * 0.35 // vertical mouse -> X rotation
      const targetY = state.mouse.x * 0.45 // horizontal mouse -> Y rotation

      group.current.rotation.x += (targetX - group.current.rotation.x) * 0.05
      group.current.rotation.y += (targetY - group.current.rotation.y) * 0.05

      // Gentle auto-floating on desktop
      const elapsedTime = state.clock.getElapsedTime()
      group.current.position.y = Math.sin(elapsedTime * 0.8) * 0.12
    }
  })

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Root_Scene">
        <group name="RootNode">
          <group name="iphone12_teardown" rotation={[-Math.PI / 2, 0, 0]}>
            <group name="front_panel" position={[0.002, 0, 0.073]}>
              <group name="front_panel_screw04" position={[0.001, 0.003, 0.07]}>
                <mesh name="front_panel_screw04_1" geometry={nodes.front_panel_screw04_1.geometry} material={materials.mat_metal} />
              </group>
              <group name="front_panel_screw03" position={[0, 0.002, 0.063]}>
                <mesh name="front_panel_screw03_1" geometry={nodes.front_panel_screw03_1.geometry} material={materials.mat_metal} />
              </group>
              <group name="front_panel_screw02" position={[0, -0.029, 0.058]}>
                <mesh name="front_panel_screw02_1" geometry={nodes.front_panel_screw02_1.geometry} material={materials.mat_metal} />
              </group>
              <group name="front_panel_screw01" position={[0, -0.028, 0.067]}>
                <mesh name="front_panel_screw01_1" geometry={nodes.front_panel_screw01_1.geometry} material={materials.mat_metal} />
              </group>
              <group name="earspeaker" position={[-0.001, -0.024, 0.045]}>
                <group name="earspeaker_1" position={[0.001, 0.011, 0.012]}>
                  <mesh name="earspeaker_2" geometry={nodes.earspeaker_2.geometry} material={materials.mat_plastic_parts} />
                  <mesh name="earspeaker_3" geometry={nodes.earspeaker_3.geometry} material={materials.mat_metal} />
                  <mesh name="earspeaker_4" geometry={nodes.earspeaker_4.geometry} material={materials.mat_parts} />
                </group>
              </group>
              <group name="front_panel_1">
                <mesh name="front_panel_2" geometry={nodes.front_panel_2.geometry} material={materials.mat_plastic_parts} />
                <mesh name="front_panel_3" geometry={nodes.front_panel_3.geometry} material={materials.mat_metal} />
                <mesh name="front_panel_4" geometry={nodes.front_panel_4.geometry} material={materials.mat_parts} />
                <mesh name="front_panel_5" geometry={nodes.front_panel_5.geometry} material={materials.mat_screen_plastic} />
                <mesh name="front_panel_6" geometry={nodes.front_panel_6.geometry} material={materials.mat_glass} />
                <mesh name="front_panel_7" geometry={nodes.front_panel_7.geometry} material={materials.mat_screen} />
              </group>
            </group>
            <group name="back_cover" position={[-0.004, 0, 0.073]}>
              <group name="back_cam_glass" position={[0, 0.017, 0.054]}>
                <group name="back_cam_hole2" position={[-0.001, 0.006, -0.007]}>
                  <group name="back_cam_hole2_1">
                    <mesh name="back_cam_hole2_2" geometry={nodes.back_cam_hole2_2.geometry} material={materials.mat_plastic_parts} />
                    <mesh name="back_cam_hole2_3" geometry={nodes.back_cam_hole2_3.geometry} material={materials.mat_screen_plastic} />
                    <mesh name="back_cam_hole2_4" geometry={nodes.back_cam_hole2_4.geometry} material={materials.mat_glass} />
                    <mesh name="back_cam_hole2_5" geometry={nodes.back_cam_hole2_5.geometry} material={materials.mat_color_body} />
                  </group>
                </group>
                <group name="back_cam_hole1" position={[-0.001, 0.006, 0.007]}>
                  <group name="back_cam_hole1_1">
                    <mesh name="back_cam_hole1_2" geometry={nodes.back_cam_hole1_2.geometry} material={materials.mat_plastic_parts} />
                    <mesh name="back_cam_hole1_3" geometry={nodes.back_cam_hole1_3.geometry} material={materials.mat_screen_plastic} />
                    <mesh name="back_cam_hole1_4" geometry={nodes.back_cam_hole1_4.geometry} material={materials.mat_glass} />
                    <mesh name="back_cam_hole1_5" geometry={nodes.back_cam_hole1_5.geometry} material={materials.mat_color_body} />
                  </group>
                </group>
                <group name="back_cam_flashlight_hole" position={[-0.001, -0.007, 0]}>
                  <group name="back_cam_flashlight_hole_1">
                    <mesh name="back_cam_flashlight_hole_2" geometry={nodes.back_cam_flashlight_hole_2.geometry} material={materials.mat_plastic_parts} />
                    <mesh name="back_cam_flashlight_hole_3" geometry={nodes.back_cam_flashlight_hole_3.geometry} material={materials.mat_glass} />
                  </group>
                </group>
                <group name="back_cam_glass_1">
                  <mesh name="back_cam_glass_2" geometry={nodes.back_cam_glass_2.geometry} material={materials.mat_metal} />
                  <mesh name="back_cam_glass_3" geometry={nodes.back_cam_glass_3.geometry} material={materials.mat_parts} />
                  <mesh name="back_cam_glass_4" geometry={nodes.back_cam_glass_4.geometry} material={materials.mat_color_body} />
                </group>
              </group>
              <group name="back_cover_1">
                <mesh name="back_cover_2" geometry={nodes.back_cover_2.geometry} material={materials.mat_metal} />
                <mesh name="back_cover_3" geometry={nodes.back_cover_3.geometry} material={materials.mat_color_body} />
              </group>
            </group>
            <group name="body">
              <group name="battery" position={[0.001, -0.017, 0.057]}>
                <group name="battery_1" position={[-0.001, 0.023, 0.008]}>
                  <mesh name="battery_2" geometry={nodes.battery_2.geometry} material={materials.mat_plastic_parts} />
                  <mesh name="battery_3" geometry={nodes.battery_3.geometry} material={materials.mat_metal} />
                  <mesh name="battery_4" geometry={nodes.battery_4.geometry} material={materials.mat_parts} />
                </group>
              </group>
              <group name="backplate" position={[-0.001, 0, 0.074]}>
                <group name="backplate_1">
                  <mesh name="backplate_2" geometry={nodes.backplate_2.geometry} material={materials.mat_metal} />
                  <mesh name="backplate_3" geometry={nodes.backplate_3.geometry} material={materials.mat_parts} />
                </group>
              </group>
              <group name="back_cam_cover" position={[0.001, 0.017, 0.127]}>
                <mesh name="back_cam_cover_1" geometry={nodes.back_cam_cover_1.geometry} material={materials.mat_metal} />
              </group>
              <group name="back_cam" position={[0, -0.005, 0.116]}>
                <group name="back_cam_1" position={[-0.002, 0.016, 0.009]}>
                  <mesh name="back_cam_2" geometry={nodes.back_cam_2.geometry} material={materials.mat_plastic_parts} />
                  <mesh name="back_cam_3" geometry={nodes.back_cam_3.geometry} material={materials.mat_metal} />
                  <mesh name="back_cam_4" geometry={nodes.back_cam_4.geometry} material={materials.mat_parts} />
                </group>
              </group>
              <group name="antenn" position={[0, -0.021, 0.112]}>
                <group name="antenn_1" position={[-0.001, 0.026, 0.009]}>
                  <mesh name="antenn_2" geometry={nodes.antenn_2.geometry} material={materials.mat_plastic_parts} />
                  <mesh name="antenn_3" geometry={nodes.antenn_3.geometry} material={materials.mat_metal} />
                  <mesh name="antenn_4" geometry={nodes.antenn_4.geometry} material={materials.mat_parts} />
                </group>
              </group>
              <group name="btn_off" position={[0, 0.034, 0.1]}>
                <mesh name="btn_off_1" geometry={nodes.btn_off_1.geometry} material={materials.mat_color_housing} />
              </group>
              <group name="btn_off_gears" position={[-0.001, 0.033, 0.101]}>
                <group name="btn_off_gears_1">
                  <mesh name="btn_off_gears_2" geometry={nodes.btn_off_gears_2.geometry} material={materials.mat_plastic_parts} />
                  <mesh name="btn_off_gears_3" geometry={nodes.btn_off_gears_3.geometry} material={materials.mat_metal} />
                </group>
              </group>
              <group name="btn_volume_down" position={[0, -0.034, 0.093]}>
                <mesh name="btn_volume_down_1" geometry={nodes.btn_volume_down_1.geometry} material={materials.mat_color_housing} />
              </group>
              <group name="btn_volume_down_gears" position={[-0.001, -0.033, 0.093]}>
                <group name="btn_volume_down_gears_1">
                  <mesh name="btn_volume_down_gears_2" geometry={nodes.btn_volume_down_gears_2.geometry} material={materials.mat_plastic_parts} />
                  <mesh name="btn_volume_down_gears_3" geometry={nodes.btn_volume_down_gears_3.geometry} material={materials.mat_metal} />
                </group>
              </group>
              <group name="btn_volume_off" position={[0, -0.035, 0.121]}>
                <group name="btn_volume_off_1">
                  <mesh name="btn_volume_off_2" geometry={nodes.btn_volume_off_2.geometry} material={materials.mat_parts} />
                  <mesh name="btn_volume_off_3" geometry={nodes.btn_volume_off_3.geometry} material={materials.mat_color_housing} />
                </group>
              </group>
              <group name="btn_volume_up" position={[0, -0.034, 0.107]}>
                <mesh name="btn_volume_up_1" geometry={nodes.btn_volume_up_1.geometry} material={materials.mat_color_housing} />
              </group>
              <group name="btn_volume_up_gears" position={[-0.001, -0.033, 0.107]}>
                <group name="btn_volume_up_gears_1">
                  <mesh name="btn_volume_up_gears_2" geometry={nodes.btn_volume_up_gears_2.geometry} material={materials.mat_plastic_parts} />
                  <mesh name="btn_volume_up_gears_3" geometry={nodes.btn_volume_up_gears_3.geometry} material={materials.mat_metal} />
                </group>
              </group>
              <group name="charging_cable" position={[0.001, -0.017, 0.067]}>
                <group name="charging_cable_1" position={[-0.001, 0.017, -0.03]}>
                  <mesh name="charging_cable_2" geometry={nodes.charging_cable_2.geometry} material={materials.mat_plastic_parts} />
                  <mesh name="charging_cable_3" geometry={nodes.charging_cable_3.geometry} material={materials.mat_metal} />
                  <mesh name="charging_cable_4" geometry={nodes.charging_cable_4.geometry} material={materials.mat_parts} />
                </group>
              </group>
              <group name="charging_port" position={[-0.001, -0.001, 0.008]}>
                <group name="charging_port_1">
                  <mesh name="charging_port_2" geometry={nodes.charging_port_2.geometry} material={materials.mat_plastic_parts} />
                  <mesh name="charging_port_3" geometry={nodes.charging_port_3.geometry} material={materials.mat_metal} />
                  <mesh name="charging_port_4" geometry={nodes.charging_port_4.geometry} material={materials.mat_color_plastic} />
                </group>
              </group>
              <group name="cover" position={[0.001, -0.018, 0.008]}>
                <mesh name="cover_1" geometry={nodes.cover_1.geometry} material={materials.mat_metal} />
              </group>
              <group name="cover_flex_cables" position={[0.001, -0.019, 0.062]}>
                <mesh name="cover_flex_cables_1" geometry={nodes.cover_flex_cables_1.geometry} material={materials.mat_metal} />
              </group>
              <group name="flashlight" position={[0, -0.011, 0.123]}>
                <group name="flashlight_1" position={[-0.002, 0.013, 0.01]}>
                  <mesh name="flashlight_2" geometry={nodes.flashlight_2.geometry} material={materials.mat_plastic_parts} />
                  <mesh name="flashlight_3" geometry={nodes.flashlight_3.geometry} material={materials.mat_metal} />
                  <mesh name="flashlight_4" geometry={nodes.flashlight_4.geometry} material={materials.mat_parts} />
                </group>
              </group>
              <group name="flashlight_dummy" position={[-0.001, 0.017, 0.122]}>
                <group name="flashlight_dummy_1">
                  <mesh name="flashlight_dummy_2" geometry={nodes.flashlight_dummy_2.geometry} material={materials.mat_plastic_parts} />
                  <mesh name="flashlight_dummy_3" geometry={nodes.flashlight_dummy_3.geometry} material={materials.mat_parts} />
                </group>
              </group>
              <group name="front_cam" position={[0, -0.017, 0.118]}>
                <group name="front_cam_1" position={[0, 0.015, 0.012]}>
                  <mesh name="front_cam_2" geometry={nodes.front_cam_2.geometry} material={materials.mat_plastic_parts} />
                  <mesh name="front_cam_3" geometry={nodes.front_cam_3.geometry} material={materials.mat_metal} />
                  <mesh name="front_cam_4" geometry={nodes.front_cam_4.geometry} material={materials.mat_parts} />
                </group>
              </group>
              <group name="front_cam_bracket" position={[0, -0.02, 0.141]}>
                <group name="front_cam_bracket_1">
                  <mesh name="front_cam_bracket_2" geometry={nodes.front_cam_bracket_2.geometry} material={materials.mat_plastic_parts} />
                  <mesh name="front_cam_bracket_3" geometry={nodes.front_cam_bracket_3.geometry} material={materials.mat_metal} />
                </group>
              </group>
              <group name="front_sensor" position={[-0.002, -0.001, 0.122]}>
                <group name="front_sensor_1" position={[0.001, -0.003, 0.01]}>
                  <mesh name="front_sensor_2" geometry={nodes.front_sensor_2.geometry} material={materials.mat_plastic_parts} />
                  <mesh name="front_sensor_3" geometry={nodes.front_sensor_3.geometry} material={materials.mat_metal} />
                  <mesh name="front_sensor_4" geometry={nodes.front_sensor_4.geometry} material={materials.mat_parts} />
                  <mesh name="front_sensor_5" geometry={nodes.front_sensor_5.geometry} material={materials.mat_plastic_parts} />
                </group>
              </group>
              <group name="inside_cam_holder" position={[-0.002, 0.021, 0.126]}>
                <mesh name="inside_cam_holder_1" geometry={nodes.inside_cam_holder_1.geometry} material={materials.mat_metal} />
              </group>
              <group name="magnets" position={[-0.003, 0, 0.074]}>
                <mesh name="magnets_1" geometry={nodes.magnets_1.geometry} material={materials.mat_metal} />
              </group>
              <group name="mic" position={[-0.001, -0.014, 0.008]}>
                <group name="mic_1">
                  <mesh name="mic_2" geometry={nodes.mic_2.geometry} material={materials.mat_plastic_parts} />
                  <mesh name="mic_3" geometry={nodes.mic_3.geometry} material={materials.mat_metal} />
                </group>
              </group>
              <group name="motherboard" position={[0, -0.014, 0.085]}>
                <group name="motherboard_1">
                  <mesh name="motherboard_2" geometry={nodes.motherboard_2.geometry} material={materials.mat_plastic_parts} />
                  <mesh name="motherboard_3" geometry={nodes.motherboard_3.geometry} material={materials.mat_metal} />
                  <mesh name="motherboard_4" geometry={nodes.motherboard_4.geometry} material={materials.mat_parts} />
                </group>
              </group>
              <group name="motherboard_cables_cover" position={[0, -0.022, 0.048]}>
                <mesh name="motherboard_cables_cover_1" geometry={nodes.motherboard_cables_cover_1.geometry} material={materials.mat_metal} />
              </group>
              <group name="motherboard_cover" position={[0.001, -0.014, 0.117]}>
                <mesh name="motherboard_cover_1" geometry={nodes.motherboard_cover_1.geometry} material={materials.mat_metal} />
              </group>
              <group name="screw_pentalobe" position={[0, 0, 0.003]}>
                <group name="screw_pentalobe_1">
                  <mesh name="screw_pentalobe_2" geometry={nodes.screw_pentalobe_2.geometry} material={materials.mat_plastic_parts} />
                  <mesh name="screw_pentalobe_3" geometry={nodes.screw_pentalobe_3.geometry} material={materials.mat_metal} />
                </group>
              </group>
              <group name="Screw01" position={[0.001, -0.021, 0.011]}>
                <mesh name="Screw01_1" geometry={nodes.Screw01_1.geometry} material={materials.mat_metal} />
              </group>
              <group name="Screw02" position={[-0.001, -0.029, 0.142]}>
                <mesh name="Screw02_1" geometry={nodes.Screw02_1.geometry} material={materials.mat_metal} />
              </group>
              <group name="Screw03" position={[-0.002, -0.02, 0.14]}>
                <mesh name="Screw03_1" geometry={nodes.Screw03_1.geometry} material={materials.mat_metal} />
              </group>
              <group name="Screw04" position={[-0.002, 0.001, 0.143]}>
                <mesh name="Screw04_1" geometry={nodes.Screw04_1.geometry} material={materials.mat_metal} />
              </group>
              <group name="Screw05" position={[0.001, 0.022, 0.143]}>
                <mesh name="Screw05_1" geometry={nodes.Screw05_1.geometry} material={materials.mat_metal} />
              </group>
              <group name="Screw06" position={[0, 0.032, 0.132]}>
                <mesh name="Screw06_1" geometry={nodes.Screw06_1.geometry} material={materials.mat_metal} />
              </group>
              <group name="Screw08" position={[0, 0.033, 0.113]}>
                <mesh name="Screw08_1" geometry={nodes.Screw08_1.geometry} material={materials.mat_metal} />
              </group>
              <group name="Screw09" position={[0, 0.033, 0.092]}>
                <mesh name="Screw09_1" geometry={nodes.Screw09_1.geometry} material={materials.mat_metal} />
              </group>
              <group name="Screw10" position={[0.001, 0.014, 0.113]}>
                <mesh name="Screw10_1" geometry={nodes.Screw10_1.geometry} material={materials.mat_metal} />
              </group>
              <group name="Screw11" position={[0.001, 0.014, 0.124]}>
                <mesh name="Screw11_1" geometry={nodes.Screw11_1.geometry} material={materials.mat_metal} />
              </group>
              <group name="Screw12" position={[0.001, 0.004, 0.111]}>
                <mesh name="Screw12_1" geometry={nodes.Screw12_1.geometry} material={materials.mat_metal} />
              </group>
              <group name="Screw13" position={[0.001, 0, 0.111]}>
                <mesh name="Screw13_1" geometry={nodes.Screw13_1.geometry} material={materials.mat_metal} />
              </group>
              <group name="Screw14" position={[0.001, 0.005, 0.131]}>
                <mesh name="Screw14_1" geometry={nodes.Screw14_1.geometry} material={materials.mat_metal} />
              </group>
              <group name="Screw15" position={[0.001, -0.007, 0.123]}>
                <mesh name="Screw15_1" geometry={nodes.Screw15_1.geometry} material={materials.mat_metal} />
              </group>
              <group name="Screw16" position={[-0.002, -0.003, 0.14]}>
                <mesh name="Screw16_1" geometry={nodes.Screw16_1.geometry} material={materials.mat_metal} />
              </group>
              <group name="Screw17" position={[0, -0.032, 0.135]}>
                <mesh name="Screw17_1" geometry={nodes.Screw17_1.geometry} material={materials.mat_metal} />
              </group>
              <group name="Screw18" position={[-0.002, -0.029, 0.129]}>
                <mesh name="Screw18_1" geometry={nodes.Screw18_1.geometry} material={materials.mat_metal} />
              </group>
              <group name="Screw19" position={[0.001, -0.028, 0.123]}>
                <mesh name="Screw19_1" geometry={nodes.Screw19_1.geometry} material={materials.mat_metal} />
              </group>
              <group name="Screw20" position={[0.001, -0.028, 0.111]}>
                <mesh name="Screw20_1" geometry={nodes.Screw20_1.geometry} material={materials.mat_metal} />
              </group>
              <group name="Screw21" position={[0, -0.032, 0.117]}>
                <mesh name="Screw21_1" geometry={nodes.Screw21_1.geometry} material={materials.mat_metal} />
              </group>
              <group name="Screw22" position={[0, -0.032, 0.124]}>
                <mesh name="Screw22_1" geometry={nodes.Screw22_1.geometry} material={materials.mat_metal} />
              </group>
              <group name="Screw23" position={[0, -0.033, 0.114]}>
                <mesh name="Screw23_1" geometry={nodes.Screw23_1.geometry} material={materials.mat_metal} />
              </group>
              <group name="Screw24" position={[0, -0.033, 0.1]}>
                <mesh name="Screw24_1" geometry={nodes.Screw24_1.geometry} material={materials.mat_metal} />
              </group>
              <group name="Screw25" position={[0, -0.033, 0.086]}>
                <mesh name="Screw25_1" geometry={nodes.Screw25_1.geometry} material={materials.mat_metal} />
              </group>
              <group name="Screw26" position={[0.001, -0.022, 0.071]}>
                <mesh name="Screw26_1" geometry={nodes.Screw26_1.geometry} material={materials.mat_metal} />
              </group>
              <group name="Screw27" position={[0.001, -0.016, 0.053]}>
                <mesh name="Screw27_1" geometry={nodes.Screw27_1.geometry} material={materials.mat_metal} />
              </group>
              <group name="Screw28" position={[0, -0.016, 0.049]}>
                <mesh name="Screw28_1" geometry={nodes.Screw28_1.geometry} material={materials.mat_metal} />
              </group>
              <group name="Screw29" position={[-0.001, -0.028, 0.052]}>
                <mesh name="Screw29_1" geometry={nodes.Screw29_1.geometry} material={materials.mat_metal} />
              </group>
              <group name="Screw30" position={[-0.001, 0.033, 0.019]}>
                <mesh name="Screw30_1" geometry={nodes.Screw30_1.geometry} material={materials.mat_metal} />
              </group>
              <group name="Screw31" position={[0, 0.029, 0.021]}>
                <mesh name="Screw31_1" geometry={nodes.Screw31_1.geometry} material={materials.mat_metal} />
              </group>
              <group name="Screw32" position={[0, 0.028, 0.005]}>
                <mesh name="Screw32_1" geometry={nodes.Screw32_1.geometry} material={materials.mat_metal} />
              </group>
              <group name="Screw33" position={[-0.002, 0.031, 0.007]}>
                <mesh name="Screw33_1" geometry={nodes.Screw33_1.geometry} material={materials.mat_metal} />
              </group>
              <group name="Screw34" position={[-0.001, 0.007, 0.01]}>
                <mesh name="Screw34_1" geometry={nodes.Screw34_1.geometry} material={materials.mat_metal} />
              </group>
              <group name="Screw35" position={[0.001, -0.005, 0.021]}>
                <mesh name="Screw35_1" geometry={nodes.Screw35_1.geometry} material={materials.mat_metal} />
              </group>
              <group name="Screw36" position={[-0.001, -0.007, 0.01]}>
                <mesh name="Screw36_1" geometry={nodes.Screw36_1.geometry} material={materials.mat_metal} />
              </group>
              <group name="Screw37" position={[0, -0.016, 0.026]}>
                <mesh name="Screw37_1" geometry={nodes.Screw37_1.geometry} material={materials.mat_metal} />
              </group>
              <group name="Screw38" position={[0.001, -0.029, 0.026]}>
                <mesh name="Screw38_1" geometry={nodes.Screw38_1.geometry} material={materials.mat_metal} />
              </group>
              <group name="Screw39" position={[0, -0.029, 0.048]}>
                <mesh name="Screw39_1" geometry={nodes.Screw39_1.geometry} material={materials.mat_metal} />
              </group>
              <group name="Screw41" position={[0, -0.033, 0.026]}>
                <mesh name="Screw41_1" geometry={nodes.Screw41_1.geometry} material={materials.mat_metal} />
              </group>
              <group name="Screw42" position={[0, -0.032, 0.017]}>
                <mesh name="Screw42_1" geometry={nodes.Screw42_1.geometry} material={materials.mat_metal} />
              </group>
              <group name="Screw43" position={[-0.001, -0.03, 0.007]}>
                <mesh name="Screw43_1" geometry={nodes.Screw43_1.geometry} material={materials.mat_metal} />
              </group>
              <group name="Screw44" position={[-0.001, -0.025, 0.005]}>
                <mesh name="Screw44_1" geometry={nodes.Screw44_1.geometry} material={materials.mat_metal} />
              </group>
              <group name="simholder" position={[0, -0.027, 0.035]}>
                <group name="simholder_1">
                  <mesh name="simholder_2" geometry={nodes.simholder_2.geometry} material={materials.mat_plastic_parts} />
                  <mesh name="simholder_3" geometry={nodes.simholder_3.geometry} material={materials.mat_color_housing} />
                </group>
              </group>
              <group name="simholder_box" position={[-0.002, -0.017, 0.046]}>
                <group name="simholder_box_1" position={[0.001, -0.007, -0.01]}>
                  <mesh name="simholder_box_2" geometry={nodes.simholder_box_2.geometry} material={materials.mat_plastic_parts} />
                  <mesh name="simholder_box_3" geometry={nodes.simholder_box_3.geometry} material={materials.mat_metal} />
                  <mesh name="simholder_box_4" geometry={nodes.simholder_box_4.geometry} material={materials.mat_parts} />
                </group>
              </group>
              <group name="simholder_cable_cover" position={[0.001, -0.023, 0.026]}>
                <mesh name="simholder_cable_cover_1" geometry={nodes.simholder_cable_cover_1.geometry} material={materials.mat_metal} />
              </group>
              <group name="speaker" position={[0, 0.012, 0.013]}>
                <group name="speaker_1">
                  <mesh name="speaker_2" geometry={nodes.speaker_2.geometry} material={materials.mat_plastic_parts} />
                  <mesh name="speaker_3" geometry={nodes.speaker_3.geometry} material={materials.mat_metal} />
                </group>
              </group>
              <group name="speaker_cover" position={[0, 0.017, 0.005]}>
                <group name="speaker_cover_1">
                  <mesh name="speaker_cover_2" geometry={nodes.speaker_cover_2.geometry} material={materials.mat_plastic_parts} />
                  <mesh name="speaker_cover_3" geometry={nodes.speaker_cover_3.geometry} material={materials.mat_parts} />
                </group>
              </group>
              <group name="taptick" position={[-0.003, -0.022, 0.026]}>
                <group name="taptick_1" position={[0.002, 0.005, -0.007]}>
                  <mesh name="taptick_2" geometry={nodes.taptick_2.geometry} material={materials.mat_plastic_parts} />
                  <mesh name="taptick_3" geometry={nodes.taptick_3.geometry} material={materials.mat_metal} />
                  <mesh name="taptick_4" geometry={nodes.taptick_4.geometry} material={materials.mat_parts} />
                </group>
              </group>
              <group name="wifi_antenn" position={[0, -0.023, 0.122]}>
                <group name="wifi_antenn_1" position={[-0.001, 0.006, 0.001]}>
                  <mesh name="wifi_antenn_2" geometry={nodes.wifi_antenn_2.geometry} material={materials.mat_plastic_parts} />
                  <mesh name="wifi_antenn_3" geometry={nodes.wifi_antenn_3.geometry} material={materials.mat_metal} />
                  <mesh name="wifi_antenn_4" geometry={nodes.wifi_antenn_4.geometry} material={materials.mat_parts} />
                </group>
              </group>
              <group name="Screw046" position={[-0.001, 0.032, 0.118]}>
                <mesh name="Screw045" geometry={nodes.Screw045.geometry} material={materials.mat_metal} />
              </group>
              <group name="Screw_special_01" position={[0, 0.004, 0.111]}>
                <mesh name="Screw_special_01_1" geometry={nodes.Screw_special_01_1.geometry} material={materials.mat_metal} />
              </group>
              <group name="Screw_special_02" position={[0, -0.028, 0.123]}>
                <mesh name="Screw_special_02_1" geometry={nodes.Screw_special_02_1.geometry} material={materials.mat_metal} />
              </group>
              <group name="wireless_charge" position={[0.001, -0.025, 0.115]}>
                <group name="wireless_charge_1" position={[-0.001, 0.025, -0.029]}>
                  <mesh name="wireless_charge_2" geometry={nodes.wireless_charge_2.geometry} material={materials.mat_plastic_parts} />
                  <mesh name="wireless_charge_3" geometry={nodes.wireless_charge_3.geometry} material={materials.mat_metal} />
                  <mesh name="wireless_charge_4" geometry={nodes.wireless_charge_4.geometry} material={materials.mat_parts} />
                </group>
              </group>
              <group name="Screw047" position={[0, -0.02, 0.143]}>
                <mesh name="Screw048" geometry={nodes.Screw048.geometry} material={materials.mat_metal} />
              </group>
              <group name="Screws_special_003" position={[-0.001, -0.011, 0.018]}>
                <mesh name="Screws_special_003_1" geometry={nodes.Screws_special_003_1.geometry} material={materials.mat_metal} />
              </group>
              <group name="Screw40" position={[-0.001, -0.025, 0.046]}>
                <mesh name="Screw40_1" geometry={nodes.Screw40_1.geometry} material={materials.mat_metal} />
              </group>
              <group name="glue_sticker" position={[-0.002, -0.001, 0.122]}>
                <mesh name="glue_sticker_1" geometry={nodes.glue_sticker_1.geometry} material={materials.mat_plastic_parts} position={[0.004, 0.002, -0.048]} />
              </group>
              <group name="grid_wires" position={[0, 0.002, 0]}>
                <mesh name="grid_wires_1" geometry={nodes.grid_wires_1.geometry} material={materials.mat_parts} />
              </group>
              <group name="inside_body" position={[-0.001, 0, 0.073]}>
                <mesh name="inside_body_1" geometry={nodes.inside_body_1.geometry} material={materials.mat_color_plastic} />
              </group>
              <group name="inside_power_port" position={[0, 0, 0.001]}>
                <mesh name="inside_power_port_1" geometry={nodes.inside_power_port_1.geometry} material={materials.mat_metal} />
              </group>
              <group name="profile_housing_bottom" position={[0, 0, 0.007]}>
                <mesh name="profile_housing_bottom_1" geometry={nodes.profile_housing_bottom_1.geometry} material={materials.mat_color_housing} />
              </group>
              <group name="profile_housing_dummies" position={[0, 0, 0.073]}>
                <mesh name="profile_housing_dummies_1" geometry={nodes.profile_housing_dummies_1.geometry} material={materials.mat_color_plastic} />
              </group>
              <group name="profile_housing_left" position={[0, -0.033, 0.073]}>
                <mesh name="profile_housing_left_1" geometry={nodes.profile_housing_left_1.geometry} material={materials.mat_color_housing} />
              </group>
              <group name="profile_housing_right" position={[0, 0.033, 0.073]}>
                <mesh name="profile_housing_right_1" geometry={nodes.profile_housing_right_1.geometry} material={materials.mat_color_housing} />
              </group>
              <group name="profile_housing_top" position={[0, 0, 0.14]}>
                <mesh name="profile_housing_top_1" geometry={nodes.profile_housing_top_1.geometry} material={materials.mat_color_housing} />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/iphone_12.glb')
